<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>Cohesive_Research</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.4871" />
  </ItemGroup>

  <!-- Debug configuration -->
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <Optimize>true</Optimize>
    <OutputPath>..\..\Assemblies\</OutputPath> <!-- Output directly to Assemblies -->
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>

  <!-- Release configuration -->
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
    <Optimize>true</Optimize>
    <OutputPath>..\..\Assemblies\</OutputPath> <!-- Output directly to Assemblies -->
    <DefineConstants>TRACE</DefineConstants>
    <DebugType>none</DebugType> <!-- Set to 'none' to exclude debug info -->
  </PropertyGroup>

</Project>
